services:
  kafka:
    image: confluentinc/confluent-local:7.9.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  producer:
    build:
      context: .
      dockerfile: ./Dockerfile.producer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      CC_BOOTSTRAP_SERVER: kafka:9092
      CC_TOPIC: ${CC_TOPIC}

  consumer:
    build:
      context: .
      dockerfile: ./Dockerfile.consumer
    depends_on:
      kafka:
        condition: service_healthy
      producer:
        condition: service_started
    environment:
      CC_BOOTSTRAP_SERVER: kafka:9092
      CC_TOPIC: ${CC_TOPIC}
