services:
  server:
    build:
      context: server
      dockerfile: Dockerfile

  envoy_service:
    image: envoyproxy/envoy:v1.33-latest
    ports:
      - "8000:8000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./descriptor.pb:/etc/envoy/descriptor.pb