services:
  server:
    build:
      context: server
      dockerfile: Dockerfile

  envoy_service:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml